export const SERVICE_TYPES = {
    REPARACAO: 'reparacao',
    INSTALACAO: 'instalacao',
    ASSISTENCIA: 'assistencia',
    MANUTENCAO: 'manutencao',
    REMOTA: 'remota',
} as const;

export const SERVICE_TYPE_LABELS: Record<string, string> = {
    [SERVICE_TYPES.REPARACAO]: 'Reparação',
    [SERVICE_TYPES.INSTALACAO]: 'Instalação',
    [SERVICE_TYPES.ASSISTENCIA]: 'Assistência',
    [SERVICE_TYPES.MANUTENCAO]: 'Manutenção',
    [SERVICE_TYPES.REMOTA]: 'Remota',
};

export const SERVICE_TYPES_LIST = [
    { id: SERVICE_TYPES.REPARACAO, label: SERVICE_TYPE_LABELS[SERVICE_TYPES.REPARACAO] },
    { id: SERVICE_TYPES.INSTALACAO, label: SERVICE_TYPE_LABELS[SERVICE_TYPES.INSTALACAO] },
    { id: SERVICE_TYPES.ASSISTENCIA, label: SERVICE_TYPE_LABELS[SERVICE_TYPES.ASSISTENCIA] },
    { id: SERVICE_TYPES.MANUTENCAO, label: SERVICE_TYPE_LABELS[SERVICE_TYPES.MANUTENCAO] },
    { id: SERVICE_TYPES.REMOTA, label: SERVICE_TYPE_LABELS[SERVICE_TYPES.REMOTA] },
];
